#
# * 32bitmicro CMSIS demo Makefile
# * $URL$
# * $ID$
#
#Copyright (c) 2009-2010, 32bitmicro
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation 
#and/or other materials provided with the distribution.
#Neither the name of the 32bitmicro nor the names of its contributors may be used to endorse or promote products derived from this software without 
#specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
#BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
#NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Commnon Sources
ASRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/startup_LPC13xx.s

CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/core_cm3.c
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/system_LPC13xx.c

ifndef NO_CLKCONFIG
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/clkconfig.c 
endif
ifndef NO_GPIO
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/gpio.c  
endif
ifndef NO_TIMER16
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/timer16.c
endif
ifndef NO_TIMER32
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/timer32.c
endif
ifndef NO_UART
CSRC+= $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/src/uart.c
endif
# Flags
CFLAGS+=-I $(LPC13XXROOT)/LPC13xx_SampleSoftware/Common/inc
LDFLAGS+=



