#
# * 32bitmicro libc api cmsis Makefile.rules
# * $URL$
# * $ID$
#
#Copyright (c) 2010, 32bitmicro
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation 
#and/or other materials provided with the distribution.
#Neither the name of the 32bitmicro nor the names of its contributors may be used to endorse or promote products derived from this software without 
#specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
#BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
#NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#  Sources
LIBC_API_ASRC=
LIBC_API_CSRC=crt0.c syscalls.c

LIBC_API_ASRC_FULL=$(addprefix $(32BITMICRO)/src/32bitmicro/libc/api/cmsis/, $(LIBC_API_ASRC))
LIBC_API_CSRC_FULL=$(addprefix $(32BITMICRO)/src/32bitmicro/libc/api/cmsis/, $(LIBC_API_CSRC))

ASRC+=$(LIBC_API_ASRC_FULL)
CSRC+=$(LIBC_API_CSRC_FULL)

# Target startup file
#TARGET_STARTUP=

# FIXME include CMSIS Makefile.Rules
AFLAGS+=-DCMSIS_API=1 
CFLAGS+=-DCMSIS_API=1 -I$(32BITMICRO)/src/32bitmicro/libc/api/cmsis
LDFLAGS+=
