#
# * 32bitmicro lpc17xx IEC60335_ClassB_CM3 Drivers Makefile rules
# * $URL$
# * $ID$
#
#Copyright (c) 2010, 32bitmicro
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation 
#and/or other materials provided with the distribution.
#Neither the name of the 32bitmicro nor the names of its contributors may be used to endorse or promote products derived from this software without 
#specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
#BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
#NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Sources
ASRC=

# CORE 
CSRC+= \
source/lpc17xx_adc.c \
source/lpc17xx_can.c \
source/lpc17xx_clkpwr.c \
source/lpc17xx_dac.c \
source/lpc17xx_emac.c \
source/lpc17xx_gpdma.c \
source/lpc17xx_gpio.c \
source/lpc17xx_i2c.c \
source/lpc17xx_i2s.c \
source/lpc17xx_libcfg_default.c \
source/lpc17xx_mcpwm.c \
source/lpc17xx_nvic.c \
source/lpc17xx_pinsel.c \
source/lpc17xx_pwm.c \
source/lpc17xx_qei.c \
source/lpc17xx_rit.c \
source/lpc17xx_rtc.c \
source/lpc17xx_spi.c \
source/lpc17xx_ssp.c \
source/lpc17xx_timer.c \
source/lpc17xx_uart.c


# Flags
AFLAGS+=
CFLAGS+=-I../Core/CM3 
CFLAGS+=-I./include 
LDFLAGS+=
