#
# * 32bitmicro lpc17xx an10916 LPC1700_FatFs_Prj  Makefile rules
# * $URL$
# * $ID$
#
#Copyright (c) 2010, 32bitmicro
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
#Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation 
#and/or other materials provided with the distribution.
#Neither the name of the 32bitmicro nor the names of its contributors may be used to endorse or promote products derived from this software without 
#specific prior written permission.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
#BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
#NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# condfiguration and defines
#_CODE_PAGE
#_USE_LFN

# Sources
ASRC=

# FatFs  
CSRC+=FatFs/ff.c
#CSRC+=FatFs/diskio.c  
CSRC+=FatFs/option/ccsbcs.c
#CSRC+=FatFs/option/cc932.c 
#CSRC+=FatFs/option/cc949.c  
#CSRC+=FatFs/option/cc936.c  
#CSRC+=FatFs/option/cc950.c  
#CSRC+=FatFs/option/syncobj.c

ASRC+=LPC1700/Core_CM3/startup_LPC17xx.s
CSRC+=LPC1700/Core_CM3/core_cm3.c
CSRC+=LPC1700/Core_CM3/system_LPC17xx.c
CSRC+=LPC1700/SPI_SD/lpc17xx_sd.c
CSRC+=LPC1700/SPI_SD/lpc17xx_spi.c
CSRC+=LPC1700/RTC/lpc17xx_rtc.c
CSRC+=LPC1700/UART/lpc17xx_uart.c
CSRC+=LPC1700/Utility/monitor.c
CSRC+=Main/main.c
# Flags
AFLAGS+=
CFLAGS+=-I./LPC1700/Core_CM3 -I./FatFs -I./LPC1700/UART -I./LPC1700/RTC -I./LPC1700/Utility 
LDFLAGS+=
